'use strict'
//var d3 = {version: "3.5.6"}
var d3 = {}
//import '../node_modules/d3/src/start.js'
//import '../node_modules/d3/src/compat/'
//import '../node_modules/d3/src/arrays/'
//import '../node_modules/d3/src/behavior/'
//import '../node_modules/d3/src/color/'
//import '../node_modules/d3/src/core/'
//import '../node_modules/d3/src/dsv/'
//import '../node_modules/d3/src/event/'
//import '../node_modules/d3/src/format/'
//import '../node_modules/d3/src/geo/'
//import '../node_modules/d3/src/geom/'
//import '../node_modules/d3/src/interpolate/'
import '../node_modules/d3/src/layout/force.js'
//import '../node_modules/d3/src/math/'
//import '../node_modules/d3/src/scale/'
//import '../node_modules/d3/src/selection/'
//import '../node_modules/d3/src/svg/'
//import '../node_modules/d3/src/time/'
//import '../node_modules/d3/src/transition/'
//import '../node_modules/d3/src/xhr/'
//import '../node_modules/d3/src/end.js'
module.exports = d3;